name: Merge

on:
  push:
    branches: [release/*]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all|write-all
    steps:
      - uses: actions/checkout@v3
      - uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

